name: GenCore
version: '1.6.2-R1'
main: com.gencore.GenCore
api-version: 1.17
authors: [ Summiner, Symmettry (Optimizer) ]
depend:
  - PlaceholderAPI
  - Vault

commands:
  GenSlots:
  GenList:
  GensList:
  GenLists:
  GensLists:
  GiveGenerator:
  GiveTank: